### ISSUE TITLE
Retransmission and packet drop message change

### ISSUE THREAD

**Issue by tmzhuang** [tmzhuang/tftp#20]
Retransmission and packet drop message change need to stand out more in output.

**Comment by brandonto** [comment]
Please fix this. It's been open for many months.

**Comment by brandonto** [comment]
Need this fixeddddddd!

**Comment by brandonto** [comment]
Fix thissssssssssssssssssssssss

**Comment by brandonto** [comment]
tianminnngggggggg fix dissss

**Comment by tmzhuang** [comment]
fixed it
